# 名称
name: weather-forcast

# 定期実行間隔
on:
  schedule:
  #10:00
  - cron: '0 22 * * *'

jobs:
  build:
    # 処理環境
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          # pipを最新版にする
          python -m pip install --upgrade pip
          # 必要なパッケージインストール
          pip install line-bot-sdk
          pip install beautifulsoup4
          pip install requests
          
      - name: Run script
        run: |
          # main.pyの実行
          python main.py
